[package]
name = "bases"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "obsidian-bases"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
obsidian-bases = { workspace = true }

